#!/bin/bash
#
# Prepares the "stack" to run apps and the environment to run buildpacks
#

#
# SYSTEM PACKAGES
#
apt-get update
xargs apt-get install -y --force-yes < /build/packages.txt
apt-get clean

#
# SUPPORTED BUILDPACKS
#
mkdir -p /build/buildpacks
cd /build/buildpacks
xargs -L 1 git clone --depth=1 < /build/buildpacks.txt

#
# MISC
#

cd /tmp
wget ftp://ftp.gnu.org/gnu/gsl/gsl-1.14.tar.gz
tar -xf gsl-1.14.tar.gz
cd gsl-1.14
./configure && make && make install

ln -sf /usr/local/lib/libgsl.so.0 /usr/lib/libgsl.so.0
ln -sf /usr/local/lib/libgsl.so.0 /usr/lib/libgsl.so
ln -sf /usr/local/lib/libgsl.so.0 /lib/libgsl.so
ln -sf /usr/local/lib/libgsl.so.0 /lib/libgsl.so.0
ln -sf /usr/local/lib/libgsl.so.0 /lib64/libgsl.so
ln -sf /usr/local/lib/libgsl.so.0 /lib64/libgsl.so.0

# Ruby buildpack system configuration
update-alternatives --set ruby /usr/bin/ruby1.9.1
update-alternatives --set gem /usr/bin/gem1.9.1
gem install bundler

